sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev \
  libsqlite3-dev python3 net-tools zlib1g-dev libsodium-dev \
  gettext wget libcurl3-gnutls ninja-build libssl-dev \
  libcurl4-gnutls-dev libevent-dev

sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev \
  libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev \
  gettext

sudo apt install tmux qemu-user make unzip

git clone https://github.com/raspberrypi/tools.git

export PATH=$PATH:$(pwd)/tools/arm-bcm2708/arm-linux-gnueabihf/bin

export target_host=arm-linux-gnueabihf

export AR=$target_host-ar
export AS=$target_host-as
export CC=$target_host-gcc
export CXX=$target_host-g++
export LD=$target_host-ld
export STRIP=$target_host-strip


git clone https://github.com/chips-blockchain/bet
cd bet
./configure
